/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Email } from "./Email";
import { EmailCountArgs } from "./EmailCountArgs";
import { EmailFindManyArgs } from "./EmailFindManyArgs";
import { EmailFindUniqueArgs } from "./EmailFindUniqueArgs";
import { CreateEmailArgs } from "./CreateEmailArgs";
import { UpdateEmailArgs } from "./UpdateEmailArgs";
import { DeleteEmailArgs } from "./DeleteEmailArgs";
import { AiAnalysis } from "../../aiAnalysis/base/AiAnalysis";
import { EmailService } from "../email.service";
@graphql.Resolver(() => Email)
export class EmailResolverBase {
  constructor(protected readonly service: EmailService) {}

  async _emailsMeta(
    @graphql.Args() args: EmailCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Email])
  async emails(@graphql.Args() args: EmailFindManyArgs): Promise<Email[]> {
    return this.service.emails(args);
  }

  @graphql.Query(() => Email, { nullable: true })
  async email(
    @graphql.Args() args: EmailFindUniqueArgs
  ): Promise<Email | null> {
    const result = await this.service.email(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Email)
  async createEmail(@graphql.Args() args: CreateEmailArgs): Promise<Email> {
    return await this.service.createEmail({
      ...args,
      data: {
        ...args.data,

        aiAnalysis: args.data.aiAnalysis
          ? {
              connect: args.data.aiAnalysis,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Email)
  async updateEmail(
    @graphql.Args() args: UpdateEmailArgs
  ): Promise<Email | null> {
    try {
      return await this.service.updateEmail({
        ...args,
        data: {
          ...args.data,

          aiAnalysis: args.data.aiAnalysis
            ? {
                connect: args.data.aiAnalysis,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Email)
  async deleteEmail(
    @graphql.Args() args: DeleteEmailArgs
  ): Promise<Email | null> {
    try {
      return await this.service.deleteEmail(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => AiAnalysis, {
    nullable: true,
    name: "aiAnalysis",
  })
  async getAiAnalysis(
    @graphql.Parent() parent: Email
  ): Promise<AiAnalysis | null> {
    const result = await this.service.getAiAnalysis(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
