/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { AiAnalysisService } from "../aiAnalysis.service";
import { AiAnalysisCreateInput } from "./AiAnalysisCreateInput";
import { AiAnalysis } from "./AiAnalysis";
import { AiAnalysisFindManyArgs } from "./AiAnalysisFindManyArgs";
import { AiAnalysisWhereUniqueInput } from "./AiAnalysisWhereUniqueInput";
import { AiAnalysisUpdateInput } from "./AiAnalysisUpdateInput";
import { EmailFindManyArgs } from "../../email/base/EmailFindManyArgs";
import { Email } from "../../email/base/Email";
import { EmailWhereUniqueInput } from "../../email/base/EmailWhereUniqueInput";

export class AiAnalysisControllerBase {
  constructor(protected readonly service: AiAnalysisService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: AiAnalysis })
  async createAiAnalysis(
    @common.Body() data: AiAnalysisCreateInput
  ): Promise<AiAnalysis> {
    return await this.service.createAiAnalysis({
      data: {
        ...data,

        task: data.task
          ? {
              connect: data.task,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,
        keyTasks: true,
        sentiment: true,
        summary: true,

        task: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [AiAnalysis] })
  @ApiNestedQuery(AiAnalysisFindManyArgs)
  async aiAnalyses(@common.Req() request: Request): Promise<AiAnalysis[]> {
    const args = plainToClass(AiAnalysisFindManyArgs, request.query);
    return this.service.aiAnalyses({
      ...args,
      select: {
        createdAt: true,
        id: true,
        keyTasks: true,
        sentiment: true,
        summary: true,

        task: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: AiAnalysis })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async aiAnalysis(
    @common.Param() params: AiAnalysisWhereUniqueInput
  ): Promise<AiAnalysis | null> {
    const result = await this.service.aiAnalysis({
      where: params,
      select: {
        createdAt: true,
        id: true,
        keyTasks: true,
        sentiment: true,
        summary: true,

        task: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: AiAnalysis })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateAiAnalysis(
    @common.Param() params: AiAnalysisWhereUniqueInput,
    @common.Body() data: AiAnalysisUpdateInput
  ): Promise<AiAnalysis | null> {
    try {
      return await this.service.updateAiAnalysis({
        where: params,
        data: {
          ...data,

          task: data.task
            ? {
                connect: data.task,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,
          keyTasks: true,
          sentiment: true,
          summary: true,

          task: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: AiAnalysis })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteAiAnalysis(
    @common.Param() params: AiAnalysisWhereUniqueInput
  ): Promise<AiAnalysis | null> {
    try {
      return await this.service.deleteAiAnalysis({
        where: params,
        select: {
          createdAt: true,
          id: true,
          keyTasks: true,
          sentiment: true,
          summary: true,

          task: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/emails")
  @ApiNestedQuery(EmailFindManyArgs)
  async findEmails(
    @common.Req() request: Request,
    @common.Param() params: AiAnalysisWhereUniqueInput
  ): Promise<Email[]> {
    const query = plainToClass(EmailFindManyArgs, request.query);
    const results = await this.service.findEmails(params.id, {
      ...query,
      select: {
        aiAnalysis: {
          select: {
            id: true,
          },
        },

        body: true,
        createdAt: true,
        id: true,
        recipient: true,
        sender: true,
        sentDate: true,
        subject: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/emails")
  async connectEmails(
    @common.Param() params: AiAnalysisWhereUniqueInput,
    @common.Body() body: EmailWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      emails: {
        connect: body,
      },
    };
    await this.service.updateAiAnalysis({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/emails")
  async updateEmails(
    @common.Param() params: AiAnalysisWhereUniqueInput,
    @common.Body() body: EmailWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      emails: {
        set: body,
      },
    };
    await this.service.updateAiAnalysis({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/emails")
  async disconnectEmails(
    @common.Param() params: AiAnalysisWhereUniqueInput,
    @common.Body() body: EmailWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      emails: {
        disconnect: body,
      },
    };
    await this.service.updateAiAnalysis({
      where: params,
      data,
      select: { id: true },
    });
  }
}
